.fp 5 CW
.de X		\" fixed width font
.nh
.ft 5
.if !\\$1 \&\\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \f1
.HY
..
.de XR
.}S 5 1 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de RX
.}S 1 5 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de XI
.}S 5 2 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de IX
.}S 2 5 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de EX		\" start example
.ta 1i 2i 3i 4i 5i 6i
.PP
.RS 
.PD 0
.ft 5
.nf
..
.de EE		\" end example
.fi
.ft
.PD
.RE
.PP
..
.TH MM2HTML 1
.SH NAME \" @(#)mm2html.1 (AT&T Labs Research) 1997-05-01
mm2html \- convert mm/man input to html
.SH SYNOPSIS
.B mm2html
[
.B \-i
.I option-file
] [
.B \-o
.I option=value
] [
.IR file .\|.\|.
]
.SH DESCRIPTION
.I mm2html
is a
.IR sed (1)
/
.IR ksh (1)
script that converts an input
.IR mm (1)
or
.IR man (1)
documents to an
.B HTML
document on the standard output.
.IR troff2html (1)
is similar but does a full
.IR troff (1)
parse.
.SS Options
.TP
.BI \-i " file"
Reads
.IR option = value
settings from
.IR file .
See
.B \-o
for a description of the option names.
Unknown options in
.I file
are ignored.
.TP
.BI \-o [no] option [= value \|.\|.\|.]
Sets options by name.
If
.B no
is specified then
.I value
is ignored and the option is turned off.
The options are:
.RS
.TP
.BI author= text
Sets the author contact information that is
placed in the document HEAD section.
.TP
.BI background= URL
The URL of the document background.
.TP
.BI logo= URL
Sets the URL of the logo/banner image that is
centered at the top of the document.
.TP
.BI mailto= address
Sets the address to send comments and suggestions.
.TP
.BI meta .name = content
Emits the HTML tag
.BI "<META NAME=" name " CONTENT=" content >.
.TP
.BI package= text
Prepended to the HTML document title.
.TP
.BI title= text
Sets the HTML document title.
.RE
.SS Extensions
Local
.B URL
links are generated for all
.BR .SH ,
.B .SS
and
.B ".H 1"
headings.
These can be referenced by embedding the benign (albeit convoluted)
.I troff
construct:
.EX
\eh'0*\ew"\fIlabel\fP"'\fItext\fP\eh'0'
.EE
where
.I label
is the local link label and
.I text
is the hot link text.
Use the following if
.I text
and
.I label
are the same:
.EX
\eh'0*1'\fItext\fP\eh'0'
.EE
.SH CAVEATS
.I mm2html
is only a script; a myriad of wierd
.IR troff (1)
constructs can blow its mind.
.SH "SEE ALSO"
html2rtf(1), ksh(1), man(1), mm(1), sed(1), troff(1), troff2html(1)
