.fp 5 CW
.de X		\" fixed width font
.nh
.ft 5
.if !\\$1 \&\\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \f1
.HY
..
.de XR
.}S 5 1 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de RX
.}S 1 5 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de XI
.}S 5 2 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de IX
.}S 2 5 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de EX		\" start example
.ta 1i 2i 3i 4i 5i 6i
.PP
.RS 
.ft 5
.nf
..
.de EE		\" end example
.fi
.ft
.RE
.PP
..
.TH TROFF2HTML 1
.SH NAME \" @(#)troff2html.1 (AT&T Labs Research) 1998-04-01
troff2html \- convert troff/groff input to html
.SH SYNOPSIS
.B troff2html
[
.B \-i
.I option-file
] [
.B \-m
.I macro-package
] [
.B \-o
.I option=value
] [
.B \-r
.I "register\|value"
] [
.B \-s
.I script
] [
.B \-v
] [
.B \-I
.I directory
] [
.I file
\&.\|.\|.
]
.SH DESCRIPTION
.I troff2html
converts input
.IR troff (1)
(or
.IR groff (1),
depending on the processing mode)
documents to an HTML document on the standard output.
Although
.I troff2html
does a full
.IR troff (1)
parse, many
.I troff
features are ignored in the mapping to HTML.
The
.I troff
.B `t'
condition test evaluates
.B true
(and the
.B `n'
condition test evaluates
.BR false ),
and the
.I groff
compatibility register
.B \e\en[.C]
evaluates to 0 (enable
.I groff
parsing) if it is referenced before the first
.I groff
.B .cp
(compatibility mode) directive.
.P
The generated HTML has properly nested begin/end tags,
even though most browsers don't care.
.SS Options
.TP
.BI \-i " file"
Reads
.IR option = value
settings from
.IR file .
See
.B \-o
for a description of the option names.
Unknown options in
.I file
are ignored.
.TP
.BI \-m " package"
Locates and reads the macro package file
.IR package .
In order to accomodate different
.I troff
installation styles the file search order is fairly involved:
.RS
.TP
.B (1)
.BI .\|/ package
.TP
.B (2)
.IB directory / package
for all
.B \-I
directories.
.TP
.B (3)
.IB directory /tmac. package
for all
.B \-I
directories.
.TP
.B (4)
.BI .\|.\|/lib/tmac/tmac. package
for all directories on
.BR $PATH .
.TP
.B (5)
.BI .\|.\|/lib/html/ package
for all directories on
.BR $PATH .
.TP
.B (6)
.BI .\|.\|/lib/html/m package .tr
for all directories on
.BR $PATH .
.RE
.TP
.BI \-o[no] option [= value \|.\|.\|.]
Sets options by name.
If
.B no
is specified then
.I value
is ignored and the option is turned off.
If
.I value
contains space characters then it must be "\|.\|.\|.\|" quoted.
Some options may only be set using the
.I troff2html
.B .xx
directive (below).
The options are:
.RS
.TP
.BI author= text
Sets the author contact information that is
placed in the document HEAD section.
.TP
.BI background= URL
The URL of the document background.
.TP
.BI debug= level
Sets the debug trace level to
.IR level .
Higher levels produce more output.
.TP
.BI footnote= char
.RB ( .xx " only)"
Starts a footnote body.
The last word emitted before
.EX
\&\f5.xx\|footnote=\fP\fIchar\fP
.EE
is the footnote hot link text.
.EX
\&\f5.xx\|nofootnote\fP
.EE
ends the footnote body.
.TP
.BI get=[+|\-] register " [" .\|.\|. ]
Traces each ``get'' for the named number registers.
.B \-
turns the tracing off.
.TP
.BI hot=[+|\-] hot-word " [" .\|.\|." ]
Adds
.RB ( + )
or
removes
.RB ( \- )
words from the
.I hot-word
list.
Constructs that match
.EX
(\fIhot-word\P ... \fIswitch-font\fP text \fIswitch-font\fP ... )
.EE
adds \f5text\fP as a hot link to another portion of the document.
.B refer
and
.B see
are the default hot words.
.TP
.BI label= label
.RB ( .xx " only)"
Emits an HTML anchor
.RI NAME= label .
.TP
.BI link=[ url \et] text
.RB ( .xx " only)"
Emits an HTML reference
.RI HREF= url
with hot link
.IR text .
If
.I url
is omitted then it is the same as
.IR text .
.TP
.BI logo= URL
Sets the URL of the logo/banner image that is
centered at the top of the document.
.TP
.BI mailto= address
Sets the address to send comments and suggestions.
.TP
.BI meta .name = content
Emits the HTML tag
.BI "<META NAME=" name " CONTENT=" content >.
.TP
.BI package= text
Prepended to the HTML document title.
.TP
.BI set=[+|\-] register " [" .\|.\|. ]
Traces each ``set'' for the named number registers.
.B \-
turns the tracing off.
.TP
.BI test= bitmask
Adds
.I bitmask
to the internal test bitmask.
Described here for completeness; use at your own risk (i.e., read the source).
.TP
.BI title= text
Sets the HTML document title.
.RE
.TP
.BI \-r " register\|value"
Sets the number register named by the single character
.I register
to the numeric expression
.IR value .
.TP
.BI \-s " script"
Reads
.I script
as if it came from a file.
For example, the following two options are equivalent:
.EX
\-s ".nr A 123"
\-r A123
.EE
.TP
.B \-v
Enables verbose error and warning messages.
Following
.I troff
tradition,
.I troff2html
by default does not warn about unknown requests;
.B \-v
enables such warnings.
.TP
.BI \-I " directory"
Appends
.I directory
to the list of directories to be searched to locate
.B \-m
and
.B \.so
files.
.SS Extensions
.B .xx
is a special
.I troff2html
request
that handles program tracing, HTML extensions and
.I troff
macro package magic that went way past the author's willingness to understand.
The syntax is:
.EX
\&.xx [no]\fIname\fP[=\fIvalue\fP]
.EE
where
.I name
and
.I value
are described under the
.B \-o
option above.
.PP
Local
.B URL
links are generated for all top level headings.
These can be referenced by embedding the benign (albeit convoluted)
.I troff
construct:
.EX
\eh'0*\ew"\fIlabel\fP"'\fItext\fP\eh'0'
.EE
where
.I label
is the local link label and
.I text
is the hot link text.
Use the following if
.I text
and
.I label
are the same:
.EX
\eh'0*1'\fItext\fP\eh'0'
.EE
Labels may be added by changing
.B *
to
.B /
in the above constructs.
.SH "SEE ALSO"
groff(1), html2rtf(1), man(1), mm(1), mm2html(1), troff(1)
