/*******************************************************************
*                                                                  *
*             This software is part of the ast package             *
*                Copyright (c) 1989-2004 AT&T Corp.                *
*        and it may only be used by you under license from         *
*                       AT&T Corp. ("AT&T")                        *
*         A copy of the Source Code Agreement is available         *
*                at the AT&T Internet web site URL                 *
*                                                                  *
*       http://www.research.att.com/sw/license/ast-open.html       *
*                                                                  *
*    If you have copied or used this software without agreeing     *
*        to the terms of the license you are infringing on         *
*           the license and copyright and are violating            *
*               AT&T's intellectual property rights.               *
*                                                                  *
*            Information and Software Systems Research             *
*                        AT&T Labs Research                        *
*                         Florham Park NJ                          *
*                                                                  *
*                 Phong Vo <kpv@research.att.com>                  *
*                                                                  *
*******************************************************************/
/* : : generated by a yacc that works -- solaris take note : : */
#ifndef _EXPARSE_H
#define _EXPARSE_H

typedef union
#ifdef __cplusplus
	EXSTYPE
#endif

{
	struct Exnode_s*expr;
	double		floating;
	struct Exref_s*	reference;
	struct Exid_s*	id;
	Sflong_t	integer;
	int		op;
	char*		string;
	struct Exbuf_s*	buffer;
} EXSTYPE;
extern EXSTYPE exlval;
# define MINTOKEN 257
# define CHAR 258
# define INT 259
# define INTEGER 260
# define UNSIGNED 261
# define FLOATING 262
# define STRING 263
# define VOID 264
# define ADDRESS 265
# define BREAK 266
# define CALL 267
# define CASE 268
# define CONSTANT 269
# define CONTINUE 270
# define DECLARE 271
# define DEFAULT 272
# define DYNAMIC 273
# define ELSE 274
# define EXIT 275
# define FOR 276
# define FUNCTION 277
# define ITERATE 278
# define ID 279
# define IF 280
# define LABEL 281
# define MEMBER 282
# define NAME 283
# define POS 284
# define PRAGMA 285
# define PRE 286
# define PRINTF 287
# define PROCEDURE 288
# define QUERY 289
# define RETURN 290
# define SCANF 291
# define SPRINTF 292
# define SSCANF 293
# define SWITCH 294
# define WHILE 295
# define F2I 296
# define F2S 297
# define I2F 298
# define I2S 299
# define S2B 300
# define S2F 301
# define S2I 302
# define F2X 303
# define I2X 304
# define S2X 305
# define X2F 306
# define X2I 307
# define X2S 308
# define OR 309
# define AND 310
# define EQ 311
# define NE 312
# define LE 313
# define GE 314
# define LS 315
# define RS 316
# define UNARY 317
# define INC 318
# define DEC 319
# define CAST 320
# define MAXTOKEN 321
#endif /* _EXPARSE_H */
