.\"
.\" G. S. Fowler
.\" D. G. Korn
.\" AT&T Bell Laboratories
.\"
.\" @(#)3d.1 (gsf@research.att.com) 10/22/91
.\"
.fp 5 CW
.de L		\" literal font
.ft 5
.if !\\$1 \&\\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \f1
..
.de LR
.}S 5 1 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de RL
.}S 1 5 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de EX		\" start example
.ta 1i 2i 3i 4i 5i 6i
.PP
.RS 
.PD 0
.ft 5
.nf
..
.de EE		\" end example
.fi
.ft
.PD
.RE
.PP
..
.TH 3D 1
.SH NAME
3d \- Enter the 3d file system environment
.SH SYNOPSIS
.B 3d
[
.B \-cnx
]
[
.B \-m
.I mount
]
[
.B \-d
.I debug
]
[
.B \-o
.I file
]
[
.B \-s
.I shell
]
[
.B \-v
.I version
]
[
.I arg
] ...
.SH DESCRIPTION
.B 3d
initiates a new shell environment which supports the 3d file system.
The
.B 3d
file system consists of two enhancements to the file system.
The first enhancement, often called viewpathing,
allows a user to create views of the file
system by putting directory trees on top of one
other.  The effect is that the top level tree appears to contain
the union of files in itself and each of the trees that it covers. 
Files are created in the top layer.  A new navigational operator,
.BR ... ,
can be used to refer to files that are covered by the top layer.
The
.BR vpath (1)
command is used to specify directory tree overlay pairs. 
The second enhancement to the file system, often called versioning,
allows an arbitrary number
of files with the same pathname to exist.
When the pathname is referenced, each process consults a
user definable
.I vmap
table to decide which version to create or select.
The
.BR vmap (1)
command is used to specify the version map table.
.PP
The
.B 3d
command acts just like
.BR sh (1)
if you are already in the 3d file system environment.
The new environment is the same as the old except that the
.B vpath
and
.B vmap
built-ins can be used to create views and version mappings
respectively.
The value of the
.SM
.B VPATH
variable determines the
initial view.
The
.B \-m
option argument
defines additional initial entries for the
.I vpath
and
.I vmap
tables.
.PP
The
.B \-n
option shows the command that would be executed to enter 3d,
but does not execute the command.
.PP
The
debug trace level can be set as an argument to the
.B \-d
option.
Higher levels cause more output to be generated for each pathname system call.
By default, the trace output will be on standard error.
However, the output file for tracing can be specified with the
argument to the
.B \-o
option.
.PP
By default,
.B 3d
executes the shell named
.B ksh
from the same directory that the
.B 3d
command 
is located.
The
argument to the
.B \-s
option defines that pathname of the shell to be executed instead.
The
.B \-c
and
.B \-x
options
and any
.I args
are passed as arguments to the shell.
.PP
By default
.B 3d
uses the highest numbered version of the 3d implementation 
found on
.SM
.BR PATH . 
The argument to the
.B \-v
option
causes the specified version of the 3d implementation to be
used instead.
.PP
.SH "SEE ALSO"
vmap(1),
vpath(1),
opaque(1),
2d(1),
ksh(1),
yeast(1).
.SH "CAVEATS"
The versioning feature of the 3d file system is not yet complete
and its use is discouraged to avoid possible compatibility
problems in future versions.
.PP
The sparc implementation uses the
.SM
.B LD_PRELOAD
variable.
