:PACKAGE: ast

LICENSE = since=1991,author=gsf

DEBUG == 1

cql :: cql.1 cql.h hix.h cql.c decl.c expr.c file.c hix.c -lcdb -ldll -lexpr

cdb :: cdb.1 cdb.c -lcdb -ldll

:TEST: cdb cql

:: 	RELEASE NOTES \
	data/big.cql data/big.db data/bot.db data/cia.cql \
	data/ciao_cc.cql data/ciao_cpp.cql data/cmp.cql data/cmp.db \
	data/countries.cql data/countries.db data/country.cql \
	data/date.cql data/date.db data/emp.cql data/emp.db \
	data/ent.db data/fanout.db data/file.db data/group.db \
	data/grp.db data/incl.cql data/incl.db data/null.cql \
	data/passwd.cql data/passwd.db data/prep3.dat data/pwd.cql \
	data/pwd.db data/rel.db data/rel.out data/sym.db \
	data/top.db data/var.db \
	data/hw.cql data/hwent.db data/hwrel.db \
	data/entity.db data/cpp.out \
	data/e.db data/r.db data/er.db data/er.cql \
	data/mem.cql data/mem.db \
	data/fix.cql data/fixcheck.cql data/fixok.db data/fixko.db \
	data/array1.cql data/array1.db data/array2.cql data/array2.db \
	data/span.db \
	data/space.cql data/space.db \
	data/fax.cql data/faxdat.db data/faxref.db
