:PACKAGE: ast

LICENSE = since=1990,author=gsf

ss :: RELEASE ss.1 ss.c -lcs

$(LIBDIR) :INSTALLDIR: group=kmem mode=ug+s,+x preserve=1 ssd

ssd :: ssd.8 ssd.c -lcs +last

$(INSTALLROOT)/share :INSTALLDIR:

$(INSTALLROOT)/share/lib/ss :INSTALLDIR:
