:PACKAGE: ast

LICENSE = since=1989,author=gsf

tw :: RELEASE PROMO.mm tw.1 tw.c expr.c ftwlocal.c -lexpr

find :: find.c LICENSE=since=1989,author=gsf+dgk

xargs :: xargs.c

locate :: locate.sh

updatedb :: updatedb.sh

:TEST: find tw xargs

:: dag.tw dot.tw du.tw ls.tw
