:PACKAGE: ast

LICENSE = since=2003,author=dgk

CCFLAGS = $(CC.OPTIMIZE) $(CC.DLL)

dsstype 1.0 plugin=ksh :LIBRARY: dsstype.c -lshell -ldss

if 0 # 2006-09-27 not yet #
:TEST: dss
end

:: RELEASE dss.tst
