.de L		\" literal font
.ft 5
.it 1 }N
.if !\\$1 \&\\$1 \\$2 \\$3 \\$4 \\$5 \\$6
..
.de LR
.}S 5 1 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de RL
.}S 1 5 \& "\\$1" "\\$2" "\\$3" "\\$4" "\\$5" "\\$6"
..
.de EX		\" start example
.ta 1i 2i 3i 4i 5i 6i
.PP
.RS 
.PD 0
.ft 5
.nf
..
.de EE		\" end example
.fi
.ft
.PD
.RE
.PP
..
.TH PROBE 1
.SH NAME \" @(#)probe.1 (gsf@research.att.com) 1998-11-11
probe \- probe language processors for tool information
.SH SYNOPSIS
.B lib/probe/probe
[
\-adgklsv
]
.I language
.I tool
.I processor
.SH DESCRIPTION
.I probe
provides command support for the
.IR libast (3)
routine
.LR pathprobe .
It maintains
.I tool
specific information for
.I language
processors.
.I lib/probe/probe
controls the language and tool specific probe command
\fBlib/probe/\fP\fIlanguage\fP\fB/\fP\fItool\fP\fB/probe\fP
and performs consistency and security checks to ensure that
the tool specific command generates valid information.
.PP
The information for the
.I langauge
processor
.I cmd
for
.I tool
resides in the file
\fBlib/probe/\fP\fIlanguage\fP\fB/\fP\fItool\fP\fB/\fP\fIXXXXXXXXPPPPPP\fP
if the
.I probe
executable is set-uid, and in
\fB$HOME/.probe/\fP\fIXXXXXXXXPPPPPP\fP
otherwise, where
.I XXXXXXXX
is a hex hash value for the fully qualified pathname for
.I cmd
and 
.I PPPPPP
is the last six character of the fully qualified pathname for
.I cmd
with
.B /
deleted and left filled with
.B .
for short paths.
.BI "lib/probe/probe \-k" " language tool cmd"
lists this pathname on the standard output.
The first line of the information file must end with the fully qualified
pathname of
.IR cmd .
This is used to detect pathname hash collisions.
.PP
The
.L pathprobe
library routine calls
.I lib/probe/probe
only when new information must be generated or the current information
is older than the tool specific probe command.
The out of date test compares the information file
.B ctime
with the probe command file
.BR mtime .
By default the information files have write permission disabled.
To handle cases where the automatic probe information is incorrect
or insufficient,
.I lib/probe/probe
will not overwrite an information file if owner write permission
is enabled.
The corrected probe information should be forwarded to the
.I tool
provider so that the tool specific probe command can be updated.
.PP
The options are provided for administrative purposes.
.PP
.TP
.B \-a
List the probe attribute definitions.
The attributes are passed as a string to the tool specific probe command.
.TP
.B \-d
Delete the current probe information file.
This is restricted to the owner of
.I processor
or
the owner of
.IR lib/probe/probe .
.TP
.B \-D
This option is for debugging.  It shows the steps that \fIprobe\fP used
in generating the configuration information for the specified language 
processor.
.TP
.B \-g
Generate the information file only if necessary.
.TP
.B \-k
List the fully qualified information file pathname.
.TP
.B \-l
List the information file contents.
.TP
.B \-s
Suppress information messages.
.TP
.B \-t
Test \- generate the information on the standard output.
The current information file is unaffected.
.TP
.B \-v
Verify the current information file by checking the fully qualified
language process pathname.
.SH EXAMPLES
To list the C language processor
.IR cc (1)
information for
.IR nmake (1):
.EX
	lib/probe/probe -l C make cc
.EE
To modify the
.IR cpp (1)
information for
.IR gcc (1):
.EX
	info=$(lib/probe/probe -k C pp gcc)
	chmod u+w $info
	edit $info
.EE
.SH FILES
.PD 0
.TP 1.5i
\fBlib/probe/\fP\fIlanguage\fP\fB/\fP\fItool\fP\fB/\fP
.I tool
specific information directory for
.I language
processors
.PD
.SH CAVEATS
To allow probe information to be generated and shared among all users
the executable
.I lib/probe/probe
must be set-uid to the owner of the
.I lib/probe
directory hierarchy.
.PP
Automatic language processor probing is mostly black magic, but then
so are most langauge processor implementations.
.SH SEE ALSO
cc(1), cpp(1), nmake(1), libast(3), pp(3)
.SH AUTHOR
Glenn Fowler
.br
AT&T Labs Research
.br
gsf@research.att.com
